version: '2.2'

services:

  mysql:
    image: mysql:5.6
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
    ports:
      - "3306:3306"
    cpu_count: 4
    mem_limit: 8192M
    mem_reservation: 512M 
